### ISSUE TITLE
[Suggestion] Blogging CMS

### ISSUE THREAD

**Issue by RyderForReal** [modrinth/blog#1]
Really sorry if this isn't supposed to go in the issues section, but I'd recommend you guys to use ghost, it's open source and free. I personally use and love it.

I think it could save you guys lots of time since it's admin panel is super easy to use.

**Comment by wafflecoffee** [comment]
It used to use ghost. This approach was found to be better

**Comment by falseresync** [comment]
Ghost has been found too greedy and enterprise-oriented for our own good. Plus this approach allows for blog for free, no server required
